export const FETCH_IMAGES = 'FETCH_IMAGES';
export const FETCH_IMAGES_PENDING = 'FETCH_IMAGES_PENDING';
export const FETCH_IMAGES_FULFILLED = 'FETCH_IMAGES_FULFILLED';
export const FETCH_IMAGES_REJECTED = 'FETCH_IMAGES_REJECTED';
export const ADD_IMAGES = 'ADD_IMAGES';
export const DELETE_IMAGES = 'DELETE_IMAGES';